---
title: "Checkpoint 3"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
  html_notebook:
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(here)
theme_set(theme_bw())

```

```{r}

series = read_csv(here("data/series_from_imdb.csv"),
                  progress = FALSE,
                  col_types = cols(.default = col_double(),
                                   series_name = col_character(),
                                   episode = col_character(),
                                   url = col_character(),
                                   season = col_character()))



```

Vamos atacar essas duas seguintes perguntas

1. Qual série possui maior diferença de avaliações de temporadas?

```{r}


series

series = series %>%
  group_by(series_name, season) %>%
  summarize(season_avg = mean(user_rating), season_rating_dist = max(user_rating) - min(user_rating))

series %>% filter(season_avg < 5.0)

ggplot(series, aes(x = season_avg, y = season_rating_dist)) +
  geom_hex()


```


2. Quanto maior o número de episódios, mais popular a série?

```{r}


```

